###
GET http://localhost:8080/products/all

###
POST http://localhost:8080/login/signin?
    username=Nguyen&
    password=123456

###
POST http://localhost:8080/login/signup
Content-Type: application/json

{
  "username": "Chi",
  "password": "123456",
  "display_name": "GVBM"
}

###
PUT http://localhost:8080/login/changePassword?
    username=Nguyen&
    password=123456&
    newPassword=654321

###
DELETE http://localhost:8080/login/delete?
    username=Chi&
    password=123456

###
GET http://localhost:8080/products/get/1

###
POST http://localhost:8080/products/post
Content-Type: application/json

{
  "name": "cefa",
  "type": "d",
  "list_price": 1,
  "discount": 0.1,
  "state": "available",
  "image": ""
}

###
DELETE http://localhost:8080/products/delete/12

###
GET http://localhost:8080/gifts/get/1

###
POST http://localhost:8080/gifts/post
Content-Type: application/json

{
  "name": "gau bong",
  "image": "",
  "quantity": 1,
  "point": -100000
}

###
DELETE http://localhost:8080/gifts/delete/8

###
GET http://localhost:8080/products/all

###
GET http://localhost:8080/gifts/all

###
GET http://localhost:8080/products/getByType?
    type=Cà phê

###
GET http://localhost:8080/products/getByName?
    name=Trà sữa truyền thống

###
PUT http://localhost:8080/products/put
Content-Type: application/json

{
  "name": "Trà sữa ô long",
  "type": "Trà sữa",
  "list_price": "30000",
  "discount": "0.0",
  "state": "unavailable"
}

###
PUT http://localhost:8080/products/putImage
Content-Type: application/json

{
  "name": "Trà sữa ô long",
  "image": ""
}

###
PUT http://localhost:8080/gifts/put
Content-Type: application/json

{
  "name": "gau bong",
  "quantity": 2,
  "point": 30000
}

###
PUT http://localhost:8080/gifts/putImage
Content-Type: application/json

{
  "name": "gau bong",
  "image": ""
}

###
GET http://localhost:8080/products/getAllByPriceAsc

###
GET http://localhost:8080/products/getAllByPriceDesc

###
GET http://localhost:8080/order/all

###
GET http://localhost:8080/order/get/1

###
GET http://localhost:8080/order/getByUserId/4

###
GET http://localhost:8080/gifts/getByName?
    name=gau bong

###
GET http://localhost:8080/login/availableGift?
    username=Hung

###
GET http://localhost:8080/login/exGifts?
    account_id=0&
    gift_id=1&
    quantity=2

###
GET http://localhost:8080/review/all

###
GET http://localhost:8080/review/get?
    user_id=3&
    product_id=4

###
GET http://localhost:8080/review/getByUserId/3

###
GET http://localhost:8080/review/getByProductId/4


###
POST http://localhost:8080/review/post
Content-Type: application/json

{
  "comment": "Quá gà",
  "score": 0,
  "customer_id": 7,
  "product_id": 3
}

###
DELETE http://localhost:8080/review/delete?
    user_id=5&
    product_id=3

###
PUT http://localhost:8080/review/put
Content-Type: application/json

{
  "comment": "quá gà",
  "score": 3,
  "customer_id": 3,
  "product_id": 5
}

###
PUT http://localhost:8080/order/addProduct
Content-Type: application/json

{
  "order_id": 5,
  "product_id": 6,
  "quantity": 1
}

###
PUT http://localhost:8080/order/removeProduct
Content-Type: application/json

{
  "order_id": 5,
  "product_id": 6
}

###
PUT http://localhost:8080/order/updateProduct
Content-Type: application/json

{
  "order_id": 5,
  "product_id": 6,
  "quantity": 2
}

###
PUT http://localhost:8080/order/setAsFinished/3

###
GET http://localhost:8080/order/getLatestByUserId/6

###
POST http://localhost:8080/order/post
Content-Type: application/json

{
  "employee_id": 5,
  "account_id": 3,
  "delivery_address": "hcmut",
  "delivery_charges": 0
}

###
DELETE http://localhost:8080/order/delete/7

###
PUT http://localhost:8080/login/changeInfo?
    id=3&
    name=kng&
    displayName=kng